[package]
name = "uuid_rust_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
